In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())

In [ ]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [ ]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [ ]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'annual_income', 'city_Delhi',
       'city_Mumbai'],
      dtype='object')

In [16]:
df = pd.get_dummies(df, columns=['city_Mumbai'])
df

,customer_id,age,gender,annual_income,city_Delhi_False,city_Delhi_True,city_Mumbai_False,city_Mumbai_True
0,1,25.0,Male,40000,True,False,False,True
1,2,35.0,Female,80000,False,True,True,False
2,3,35.0,Female,60000,False,True,True,False
3,4,35.0,Male,120000,True,False,False,True
4,2,35.0,Female,80000,False,True,True,False
5,5,40.0,Male,95000,False,True,True,False

In [19]:
le = LabelEncoder()

In [21]:
df['gender'] = le.fit_transform(df['gender'])
df

,customer_id,age,gender,annual_income,city_Delhi_False,city_Delhi_True,city_Mumbai_False,city_Mumbai_True
0,1,25.0,1,40000,True,False,False,True
1,2,35.0,0,80000,False,True,True,False
2,3,35.0,0,60000,False,True,True,False
3,4,35.0,1,120000,True,False,False,True
4,2,35.0,0,80000,False,True,True,False
5,5,40.0,1,95000,False,True,True,False

In [22]:
print("Encoded DataFrame:\n")
print(df.head())

Encoded DataFrame:

   customer_id   age  gender  annual_income  city_Delhi_False  \
0            1  25.0       1          40000              True
1            2  35.0       0          80000             False
2            3  35.0       0          60000             False
3            4  35.0       1         120000              True
4            2  35.0       0          80000             False

   city_Delhi_True  city_Mumbai_False  city_Mumbai_True
0            False              False              True
1             True               True             False
2             True               True             False
3            False              False              True
4             True               True             False

In [23]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [26]:
num_cols = ['age', 'annual_income']
minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df[num_cols])
print("\nMin-Max Scaler Data:\n")
print(df_minmax.head())

Min-Max Scaler Data:

   customer_id       age  gender  annual_income  city_Delhi_False  \
0            1  0.000000       1           0.00              True
1            2  0.666667       0           0.50             False
2            3  0.666667       0           0.25             False
3            4  0.666667       1           1.00              True
4            2  0.666667       0           0.50             False

   city_Delhi_True  city_Mumbai_False  city_Mumbai_True
0            False              False              True
1             True               True             False
2             True               True             False
3            False              False              True
4             True               True             False

In [27]:
standard = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = standard.fit_transform(df[num_cols])
print("\nStandardized Data:\n")
print(df_standard.head())

Standardized Data:

   customer_id       age  gender  annual_income  city_Delhi_False  \
0            1 -2.042649       1      -1.552077              True
1            2  0.185695       0       0.033023             False
2            3  0.185695       0      -0.759527             False
3            4  0.185695       1       1.618123              True
4            2  0.185695       0       0.033023             False

   city_Delhi_True  city_Mumbai_False  city_Mumbai_True
0            False              False              True
1             True               True             False
2             True               True             False
3            False              False              True
4             True               True             False